name: 'taxi_analytics'
version: '1.0.0'
config-version: 2
profile: 'taxi_analytics'
model-paths: ["models"]
target-path: "target"
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

on-run-end:
  - 'GRANT USAGE ON SCHEMA public TO "user";'
  - 'GRANT SELECT ON ALL TABLES IN SCHEMA public TO "user";'